// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("backend.Models.Learner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgeBand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AiFamiliarity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AttendanceRisk")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceAccess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DigitalConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InternetAccess")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LearnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProgrammingConfidence")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RiskScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SupportNeed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Learners");
                });
#pragma warning restore 612, 618
        }
    }
}
